/**
 * Copyright (C) 2014 Michael Röder (michael.roeder@unister.de)
 *
 * Licensed under the Creative Commons Attribution-NonCommercial 4.0
 * International Public License (the "License").
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://creativecommons.org/licenses/by-nc/4.0/legalcode
 *
 * Unless required by applicable law or agreed to in writing, a file
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.aksw.palmetto.prob;

public interface InverseProbabilitySupplier {

    /**
     * This method retrieves the probability P(W',¬W*) of the two given word set definitions for the word set W' and the
     * inverting word set W*.
     * 
     * @param wordSetDef
     *            - definition of the fixed part of the word set
     * @param invertingWordSet
     *            - the inverted word set
     * @param probabilities
     *            - probability array generated by a {@link ProbabilitySupplier}
     * @return the inverse probability
     */
    @Deprecated
    public double getInverseProbability(int wordSetDef, int invertingWordSet, double probabilities[]);
}
